### PR TITLE
General Improvements and new feature

### PR DESCRIPTION
**Pull request by rtu-dataframe**
- Added support to send email after successful backup job with the current backup details: added $EXIM_SMARTHOST_NAME, $EXIM_SMARTHOST_FROM, $EXIM_SMARTHOST_TO environment variables
- Added to the base Dockerfiles (backup/Postgres) the Netcat utility tool, to communicate with the exim container while sending an email report
- Updated readme files with the new information and examples
- Fixed some small typos

### CODE REVIEW

**Comment by rtu-dataframe** [comment]
@rsoika before merging wait for a new message, i'm currently improving the email sending section of the script

**Comment by rtu-dataframe** [comment]
@rsoika i've updated the sendmail script function, it seems that everything can be merged without any issue.

**Comment by rsoika** [comment]
great! the email feature is very helpful

**Review by rsoika — COMMENTED** [review]
ok

**Pull request merged**
