### PR TITLE
EXIM_* variable export to crontab scripts

### PR DESCRIPTION
**Pull request by rtu-dataframe**

### CODE REVIEW

**Comment by rsoika** [comment]
Maybe its better to rename the variables prafix from

    EXIM_SMARTHOST_NAME 
    EXIM_SMARTHOST_FROM
    EXIM_SMARTHOST_TO

to

    BACKUP_EMAIL_SMARTHOST 
    BACKUP_EMAIL_FROM
    BACKUP_EMAIL_TO

What do you think?

**Comment by rtu-dataframe** [comment]
You know what? I totally agree!

Let me push the refactoring with the above changes

**Comment by rtu-dataframe** [comment]
@rsoika, refactoring completed and fully tested on my development & production environment!

Have a great day!

**Comment by rsoika** [comment]
Thanks a lot for your contribution!

**Pull request merged**
