### PR TITLE
Dockerfile updates and some small optimization

### PR DESCRIPTION
**Pull request by rtu-dataframe**
HI! I'm using this image on my systems and i have done some small changes in order to update it and make it more flexible:

- Updated the base image of backup Dockerfile to the latest Debian Buster slim
- Added BACKUP_ROOT_DIR in order to manage in a more flexible way the remote base backup folder
- Small improvements on docs as required for adding the BACKUP_ROOT_DIR environment variable

### CODE REVIEW

**Comment by rsoika** [comment]
Great! Thanks for your improvements. 
I will merge your pull request soon. But I must first think about the new BACKUP_ROOT_DIR if this influences my own containers. Do I need to add the new environment variable in any case? Or is there a default value ...?

**Comment by rtu-dataframe** [comment]
👍  I'm pushing right now a new commit with the default fallback!

**Comment by rtu-dataframe** [comment]
@rsoika, done, added default value if BACKUP_ROOT_DIR environment variable it's not set

**Comment by rsoika** [comment]
@Simonefardella  - great work!

**Comment by rsoika** [comment]
pushed tag version 1.2.10 and latest to dockerhub

**Pull request merged**
